language: ruby

services:
- docker

before_install:
  - docker build -t parthpower/ytdl_express .
  - docker run -p 127.0.0.1:8080:8080 -d parthpower/ytdl_express
  - docker ps -a

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push parthpower/ytdl_express

script:
  - echo "Done"
